services:
  postgres:
    image: postgres:15
    container_name: mlops_postgres
    environment:
      POSTGRES_DB: mlops_db
      POSTGRES_USER: mlops_user
      POSTGRES_PASSWORD: mlops_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops_user -d mlops_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mlflow:
    image: python:3.10-slim
    container_name: mlops_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./models:/models
    working_dir: /app
    command: >
      sh -c "
        apt-get update && apt-get install -y curl &&
        pip install mlflow==2.8.1 &&
        mlflow server
          --backend-store-uri /mlruns
          --default-artifact-root /mlruns
          --host 0.0.0.0
          --port 5000
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build: .
    container_name: mlops_streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mlops_db
      - POSTGRES_USER=mlops_user
      - POSTGRES_PASSWORD=mlops_password
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: >
      sh -c "
        uv run streamlit run src/dashboard/streamlit_app.py 
          --server.address 0.0.0.0 
          --server.port 8501
          --server.headless true
      "
    depends_on:
      - postgres
      - mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
