[project]
name = "mlops-2025-final-project"
version = "0.1.0"
description = "Premier League Match Predictor - ML-powered app for predicting football match outcomes"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.3.0",
    "mlflow>=2.5.0",
    "prefect>=2.10.0",
    "evidently>=0.4.0",
    "requests>=2.31.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.23.0",
    "pydantic>=2.0.0",
    "click>=8.1.0",
    "python-dotenv>=1.0.0",
    "jupyter>=1.0.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "pre-commit>=3.3.0",
    "mypy>=1.5.0",
    "pandas-stubs>=2.0.0",
    "types-requests>=2.31.0",
    "types-seaborn>=0.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["mlflow"]
force_alphabetical_sort_within_sections = true
skip_gitignore = true
force_single_line = false

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=src --cov-report=html --cov-report=term-missing"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]

[dependency-groups]
dev = [
    "autoflake>=2.3.1",
    "pandas-stubs>=2.3.0.250703",
    "pre-commit>=4.2.0",
    "types-requests>=2.32.4.20250611",
    "types-seaborn>=0.13.2.20250516",
]
