services:
  - type: web
    name: premier-league-mlops
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MLFLOW_TRACKING_URI
        value: sqlite:///mlflow.db
      - key: MODEL_REGISTRATION_THRESHOLD
        value: "0.6"
      - key: PORT
        value: "8000"

  - type: pserv
    name: premier-league-postgres
    env: docker
    dockerfilePath: ./Dockerfile.postgres
    region: oregon
    plan: free
    branch: main
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: mlops-db
    databaseName: mlops_db
    user: mlops_user
    region: oregon
    plan: free
