backup_model_dir: models/backups
check_interval_minutes: 60
drift_threshold: 0.1
enable_automatic_deployment: false
max_concurrent_retraining: 1
max_days_without_retraining: 30
max_predictions_without_retraining: 1000
min_days_between_retraining: 7
min_new_predictions: 100
min_validation_accuracy: 0.45
model_path: models/model.pkl
monitoring_output_dir: evaluation_reports
performance_threshold: 0.05
training_data_path: data/real_data/premier_league_matches.parquet
validation_improvement_required: 0.01
