# Automated Retraining Configuration
# This file contains the configuration for the automated retraining system

# Performance thresholds
performance_threshold: 0.05  # Trigger if accuracy drops by 5%
drift_threshold: 0.1  # Trigger if drift score exceeds 10%

# Time-based triggers
max_days_without_retraining: 30  # Maximum days without retraining
min_days_between_retraining: 7   # Minimum days between retraining attempts

# Data volume triggers
min_new_predictions: 100          # Minimum predictions before considering retraining
max_predictions_without_retraining: 1000  # Maximum predictions before forcing retraining

# Validation requirements
min_validation_accuracy: 0.45     # Don't deploy if worse than 45%
validation_improvement_required: 0.01  # Must improve by 1% to deploy

# File paths
model_path: "models/model.pkl"
backup_model_dir: "models/backups"
training_data_path: "data/real_data/premier_league_matches.parquet"
monitoring_output_dir: "evaluation_reports"

# Scheduler settings
check_interval_minutes: 60        # Check triggers every hour
enable_automatic_deployment: false  # Require manual approval for safety
max_concurrent_retraining: 1      # Only one retraining at a time
